/**
 * Datos anatómicos y radiológicos de alta precisión para el Laboratorio de Anatomía
 * Categorizados por modalidades: Rayos X (RX), Tomografía Computarizada (CT), Resonancia Magnética (IRM/RM), Ultrasonido (US)
 */

export type ModalityCategory = 'TODAS' | 'RAYOS_X' | 'CT' | 'IRM' | 'ULTRASONIDO'

export interface AnatomicalStructure {
  id: string
  name: string
  shortName: string
  x: number // Porcentaje 0 - 100 en el eje X de la imagen radiológica
  y: number // Porcentaje 0 - 100 en el eje Y de la imagen radiológica
  description: string
  clinicalSignificance: string
  radiologicalDensity: string
}

export interface AnatomyStudy {
  id: string
  title: string
  category: ModalityCategory
  modality: 'Rayos X (RX)' | 'Tomografía Computarizada (CT)' | 'Resonancia Magnética (IRM)' | 'Ultrasonido (US)'
  projection: string
  description: string
  imageUrl: string
  svgGraphic: string
  structures: AnatomicalStructure[]
}

export const MODALITY_CATEGORIES: { key: ModalityCategory; label: string; icon: string; count?: number }[] = [
  { key: 'TODAS', label: 'Todas las Modalidades', icon: 'Sparkles' },
  { key: 'RAYOS_X', label: 'Rayos X Convencional (RX)', icon: 'Radiation' },
  { key: 'CT', label: 'Tomografía Computarizada (CT/TAC)', icon: 'Layers' },
  { key: 'IRM', label: 'Resonancia Magnética (IRM/RM)', icon: 'Magnet' },
  { key: 'ULTRASONIDO', label: 'Ecografía / Ultrasonido (US)', icon: 'Activity' },
]

export const ANATOMY_STUDIES: AnatomyStudy[] = [
  // ─── 1. RAYOS X (RX) ────────────────────────────────────────────────────────
  {
    id: 'torax-pa',
    title: 'Tórax PA (Posteroanterior)',
    category: 'RAYOS_X',
    modality: 'Rayos X (RX)',
    projection: 'Bipedestación - PA',
    description: 'Estudio fundamental para evaluar parénquima pulmonar, silueta cardiaca, mediastino y reja costal.',
    imageUrl: '/lab-images/torax_pa.jpg',
    svgGraphic: 'chest',
    structures: [
      {
        id: 'traquea',
        name: 'Tráquea (Columna Aérea)',
        shortName: 'Tráquea',
        x: 50,
        y: 16,
        description: 'Estructura tubular central radiolúcida (oscura) que transporta aire hacia los bronquios principales.',
        clinicalSignificance: 'Su desviación puede sugerir atelectasia, neumotórax a tensión o masas mediastínicas.',
        radiologicalDensity: 'Radiolúcido (Negro/Gris)',
      },
      {
        id: 'clavicula-der',
        name: 'Clavícula Derecha (Extremo Medial y Cuerpo)',
        shortName: 'Clavícula Der.',
        x: 24,
        y: 12,
        description: 'Hueso largo horizontal que cruza los ápices pulmonares superiores.',
        clinicalSignificance: 'La simetría de sus extremos mediales con respecto a las apófisis espinosas evalúa la correcta rotación del paciente.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'boton-aortico',
        name: 'Botón Aórtico (Cayado de la Aorta)',
        shortName: 'Botón Aórtico',
        x: 56,
        y: 31,
        description: 'Prominencia convexa radiopaca en el borde superior izquierdo del mediastino.',
        clinicalSignificance: 'El desenrollamiento o calcificación aórtica es frecuente en hipertensión o ateromatosis.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'silueta-cardiaca',
        name: 'Ventrículo Izquierdo / Silueta Cardíaca',
        shortName: 'Silueta Cardíaca',
        x: 64,
        y: 64,
        description: 'Borde inferior izquierdo del corazón que forma la curvatura principal hacia el ápice cardíaco.',
        clinicalSignificance: 'Permite calcular el Índice Cardiotorácico (ICT); un valor > 0.50 en adultos indica cardiomegalia.',
        radiologicalDensity: 'Radiopaco (Densidad Agua/Tejido Blando)',
      },
      {
        id: 'cupula-diafragmatica-der',
        name: 'Cúpula Diafragmática Derecha',
        shortName: 'Hemidiafragma Der.',
        x: 26,
        y: 77,
        description: 'Contorno convexo radiopaco del diafragma derecho, situado 1 a 2 cm más alto que el izquierdo por la presencia del hígado.',
        clinicalSignificance: 'La presencia de aire por debajo (signo de Popper / creciente aéreo) indica neumoperitoneo (urgencia quirúrgica).',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'burbuja-gastrica',
        name: 'Cámara Gástrica (Burbuja de Aire en Fundus)',
        shortName: 'Burbuja Gástrica',
        x: 70,
        y: 81,
        description: 'Colección de aire fisiológica radiolúcida situada por debajo del hemidiafragma izquierdo.',
        clinicalSignificance: 'Referencia anatómica normal para identificar el lado izquierdo y descartar situs inversus.',
        radiologicalDensity: 'Radiolúcido (Gas/Aire)',
      },
      {
        id: 'seno-costofrenico-der',
        name: 'Seno Costofrénico Derecho',
        shortName: 'Seno Costofrénico Der.',
        x: 10,
        y: 84,
        description: 'Ángulo lateral derecho agudo y afilado entre el diafragma y la pared costal.',
        clinicalSignificance: 'Debe ser siempre nítido y libre; su velamiento u ocupación sugiere derrame pleural o engrosamiento fibroso.',
        radiologicalDensity: 'Radiolúcido (Ángulo Libre)',
      },
      {
        id: 'seno-costofrenico-izq',
        name: 'Seno Costofrénico Izquierdo',
        shortName: 'Seno Costofrénico Izq.',
        x: 90,
        y: 84,
        description: 'Ángulo lateral izquierdo formado entre la cúpula diafragmática y la pared costal torácica.',
        clinicalSignificance: 'El borramiento es el signo radiológico inicial de derrame pleural acumulado en decúbito o bipedestación.',
        radiologicalDensity: 'Radiolúcido (Ángulo Libre)',
      },
    ],
  },
  {
    id: 'craneo-lateral',
    title: 'Cráneo AP / Frontal',
    category: 'RAYOS_X',
    modality: 'Rayos X (RX)',
    projection: 'Anteroposterior (AP / Caldwell)',
    description: 'Visualización de la bóveda craneal, órbitas, celdillas etmoidales, senos frontales y maxilar.',
    imageUrl: '/lab-images/craneo_lateral.jpg',
    svgGraphic: 'skull',
    structures: [
      {
        id: 'calota-craneal',
        name: 'Calota Craneal / Bóveda Ósea',
        shortName: 'Calota Craneal',
        x: 50,
        y: 14,
        description: 'Láminas óseas compactas que forman la convexidad superior del cráneo.',
        clinicalSignificance: 'Detección de líneas de fractura radiolúcidas, lesiones líticas o hipertensión endocraneana.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'seno-frontal',
        name: 'Seno Frontal',
        shortName: 'Seno Frontal',
        x: 50,
        y: 41,
        description: 'Cavidad neumática radiolúcida en el hueso frontal sobre la raíz nasal.',
        clinicalSignificance: 'La opacificación o niveles hidroaéreos indican sinusitis o fractura de pared anterior/posterior.',
        radiologicalDensity: 'Radiolúcido (Negro/Gris)',
      },
      {
        id: 'orbitas',
        name: 'Cavidad Orbitaria (Reborde Orbitario)',
        shortName: 'Órbitas Oculares',
        x: 34,
        y: 48,
        description: 'Contorno redondeado radiopaco que aloja el globo ocular y musculatura extrínseca.',
        clinicalSignificance: 'Búsqueda de fracturas por estallido (blow-out fracture) de suelo orbitario.',
        radiologicalDensity: 'Radiopaco / Radiolúcido central',
      },
      {
        id: 'tabique-nasal',
        name: 'Tabique y Fosas Nasales',
        shortName: 'Fosa Nasal',
        x: 50,
        y: 60,
        description: 'Estructura osteocartilaginosa media que divide ambas cavidades nasales.',
        clinicalSignificance: 'Evalúa desviaciones septales, hipertrofia de cornetes y fracturas nasales.',
        radiologicalDensity: 'Radiolúcido / Radiopaco',
      },
      {
        id: 'mandibula',
        name: 'Mandíbula y Sínfisis Mentoniana',
        shortName: 'Mandíbula',
        x: 50,
        y: 84,
        description: 'Hueso impar móvil inferior del macizo facial.',
        clinicalSignificance: 'Descarte de fracturas parasinfisarias o del ángulo mandibular tras traumatismo facial.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
    ],
  },
  {
    id: 'columna-lumbar',
    title: 'Columna Lumbar Lateral',
    category: 'RAYOS_X',
    modality: 'Rayos X (RX)',
    projection: 'Proyección Lateral Estricta (T12 - S2)',
    description: 'Evaluación anatómica completa del raquis lumbar: cuerpos vertebrales L1 a L5, espacios discales, forámenes intervertebrales, pars interarticularis, apófisis espinosas y segmentos sacros S1-S2.',
    imageUrl: '/lab-images/columna_lumbar.jpg',
    svgGraphic: 'spine',
    structures: [
      {
        id: 'cuerpo-l1',
        name: 'Cuerpo Vertebral Lumbar Superior (L1)',
        shortName: 'Cuerpo L1',
        x: 46,
        y: 20,
        description: 'Primera vértebra lumbar situada justo por debajo de la charnela toracolumbar (T12).',
        clinicalSignificance: 'Sitio más frecuente de fractura por compresión en traumatismos de alta energía y osteoporosis.',
        radiologicalDensity: 'Radiopaco (Hueso Cortical y Trabecular)',
      },
      {
        id: 'cuerpo-l2',
        name: 'Cuerpo Vertebral L2',
        shortName: 'Cuerpo L2',
        x: 43,
        y: 32,
        description: 'Bloque óseo cuadrangular superior con trabeculado óseo y altura conservada.',
        clinicalSignificance: 'Nivel habitual de finalización del cono medular espinal.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
      {
        id: 'cuerpo-l3',
        name: 'Cuerpo Vertebral L3 (Ápice de Lordosis)',
        shortName: 'Cuerpo L3',
        x: 40,
        y: 44,
        description: 'Vértebra central que conforma el punto de máxima convexidad anterior de la lordosis fisiológica.',
        clinicalSignificance: 'Evaluación de la alineación raquídea sagital y osteofitos marginales.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
      {
        id: 'cuerpo-l4',
        name: 'Cuerpo Vertebral L4',
        shortName: 'Cuerpo L4',
        x: 39,
        y: 57,
        description: 'Vértebra lumbar inferior que soporta gran carga mecánica axial.',
        clinicalSignificance: 'Nivel frecuente de espondilolistesis degenerativa anterior por artrosis facetaria.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
      {
        id: 'cuerpo-l5',
        name: 'Cuerpo Vertebral L5 (Transición Lumbosacra)',
        shortName: 'Cuerpo L5',
        x: 42,
        y: 70,
        description: 'Última vértebra lumbar con morfología cuneiforme que se inclina sobre la base del sacro.',
        clinicalSignificance: 'Zona de máxima sobrecarga y mayor frecuencia de espondilolisis (fractura de pars) y espondilolistesis ístmica.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
      {
        id: 'espacio-l4-l5',
        name: 'Disco Intervertebral L4-L5',
        shortName: 'Disco L4-L5',
        x: 39,
        y: 64,
        description: 'Espacio radiolúcido correspondiente a la almohadilla cartilaginosa entre L4 y L5.',
        clinicalSignificance: 'El pinzamiento y presencia de gas (fenómeno de vacío discal) indica discopatía degenerativa severa.',
        radiologicalDensity: 'Radiolúcido (Cartílago Intervertebral)',
      },
      {
        id: 'espacio-l5-s1',
        name: 'Disco Intervertebral L5-S1 (Espacio Lumbosacro)',
        shortName: 'Disco L5-S1',
        x: 47,
        y: 76,
        description: 'Espacio discal oblicuo cartilaginoso entre la cara inferior de L5 y la plataforma de S1.',
        clinicalSignificance: 'Localización más frecuente de hernia discal con compresión de la raíz S1 (ciática).',
        radiologicalDensity: 'Radiolúcido (Negro/Gris)',
      },
      {
        id: 'sacro-s1',
        name: 'Promontorio Sacro y Plataforma Superior de S1',
        shortName: 'Promontorio S1',
        x: 50,
        y: 80,
        description: 'Plataforma ósea articular superior de la primera vértebra sacra.',
        clinicalSignificance: 'Punto de referencia clave para trazar la línea lordótica de Ferguson y el ángulo lumbosacro.',
        radiologicalDensity: 'Radiopaco (Hueso Cortical denso)',
      },
      {
        id: 'sacro-s2',
        name: 'Segmento Sacro S2 / Cuerpo Sacro',
        shortName: 'Sacro (S2)',
        x: 56,
        y: 88,
        description: 'Masa ósea fusionada del sacro que forma la pared posterior de la pelvis.',
        clinicalSignificance: 'Descarte de fracturas por insuficiencia sacra en pacientes osteoporóticos.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'foramen-neural',
        name: 'Agujero de Conjunción (Foramen Intervertebral L3-L4)',
        shortName: 'Foramen Neural',
        x: 51,
        y: 48,
        description: 'Orificio oval radiolúcido delimitado por los pedículos vertebrales por donde emerge la raíz nerviosa.',
        clinicalSignificance: 'La disminución de su calibre (estenosis foraminal) provoca radiculopatía compresiva.',
        radiologicalDensity: 'Radiolúcido (Canal Libre)',
      },
      {
        id: 'pars-interarticularis',
        name: 'Pars Interarticularis / Istmo Vertebral',
        shortName: 'Pars Interarticularis',
        x: 54,
        y: 52,
        description: 'Puente óseo de la lámina vertebral entre las apófisis articulares superior e inferior.',
        clinicalSignificance: 'El trazo radiolúcido de fractura en la pars (signo del "perro con collar de LaChapelle") diagnostica espondilolisis.',
        radiologicalDensity: 'Radiopaco (Istmo Óseo)',
      },
      {
        id: 'apofisis-espinosa',
        name: 'Proceso Espinoso / Apófisis Espinosa (Posterior)',
        shortName: 'Proceso Espinoso',
        x: 64,
        y: 50,
        description: 'Proyección ósea dorsal donde se anclan los ligamentos interespinales y supraespinosos.',
        clinicalSignificance: 'Referencia anatómica palpable para punciones lumbares y anestesia raquídea.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
    ],
  },
  {
    id: 'pelvis-ap',
    title: 'Pelvis Ósea y Articulación Coxofemoral AP',
    category: 'RAYOS_X',
    modality: 'Rayos X (RX)',
    projection: 'Anteroposterior (AP)',
    description: 'Evaluación integral del anillo pelviano, articulaciones sacroilíacas, cotilos acetabulares, cabezas femorales y cuello femoral.',
    imageUrl: '/lab-images/pelvis_ap.jpg',
    svgGraphic: 'pelvis',
    structures: [
      {
        id: 'cresta-iliaca-der',
        name: 'Cresta y Ala Ilíaca Derecha',
        shortName: 'Cresta Ilíaca',
        x: 23,
        y: 15,
        description: 'Borde superior convexo del hueso ilíaco con su fosa ilíaca interna amplia.',
        clinicalSignificance: 'Sitio de inserción de la musculatura abdominal y toma de injertos óseos o biopsias de médula.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
      {
        id: 'articulacion-sacroiliaca',
        name: 'Articulación Sacroilíaca Derecha',
        shortName: 'Art. Sacroilíaca',
        x: 37,
        y: 22,
        description: 'Articulación sinovial/sindesmosis oblicua que transmite el peso del raquis hacia la pelvis.',
        clinicalSignificance: 'El estrechamiento o esclerosis articular es el signo radiológico típico de la sacroileítis en Espondilitis Anquilosante.',
        radiologicalDensity: 'Radiolúcido / Radiopaco subcondral',
      },
      {
        id: 'acetabulo-der',
        name: 'Acetábulo y Techo Cotiloideo Derecho',
        shortName: 'Techo Acetabular',
        x: 28,
        y: 53,
        description: 'Cúpula hemisférica ósea del ilion que aloja la cabeza del fémur.',
        clinicalSignificance: 'La pérdida de espacio articular superior y osteofitos marginales caracterizan la artrosis coxofemoral (coxartrosis).',
        radiologicalDensity: 'Radiopaco (Hueso Subcondral)',
      },
      {
        id: 'cabeza-femoral-der',
        name: 'Cabeza Femoral Derecha',
        shortName: 'Cabeza Femoral',
        x: 27,
        y: 60,
        description: 'Superficie esférica lisa y convexa que articula congruentemente con el acetábulo.',
        clinicalSignificance: 'La pérdida de esfericidad o signo de la media luna alerta de Necrosis Avascular (NAV) de cadera.',
        radiologicalDensity: 'Radiopaco (Hueso Esférico)',
      },
      {
        id: 'cuello-femoral-der',
        name: 'Cuello Femoral Derecho (Línea Cervical)',
        shortName: 'Cuello Femoral',
        x: 18,
        y: 64,
        description: 'Segmento óseo oblicuo que une la cabeza con la diáfisis femoral.',
        clinicalSignificance: 'Lugar de fracturas intracapsulares subcapitales y transcervicales en ancianos con osteoporosis.',
        radiologicalDensity: 'Radiopaco (Trabéculas de Compresión y Tensión)',
      },
      {
        id: 'trocanter-mayor-der',
        name: 'Trocánter Mayor Derecho',
        shortName: 'Trocánter Mayor',
        x: 10,
        y: 67,
        description: 'Gran prominencia ósea lateral para la inserción de los músculos glúteo medio y menor.',
        clinicalSignificance: 'Límite lateral en fracturas extracapsulares pertrocantéricas.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'sinfisis-pubica',
        name: 'Sínfisis del Pubis (Línea Media)',
        shortName: 'Sínfisis Púbica',
        x: 50,
        y: 72,
        description: 'Articulación anfiartrosis fibrocartilaginosa que une los dos cuerpos púbicos en la línea media.',
        clinicalSignificance: 'Una diástasis > 5-10 mm indica rotura traumática grave del anillo pelviano (fractura en libro abierto).',
        radiologicalDensity: 'Radiolúcido Central (~4-5 mm)',
      },
      {
        id: 'agujero-obturador-der',
        name: 'Agujero Obturador Derecho',
        shortName: 'Agujero Obturador',
        x: 39,
        y: 72,
        description: 'Gran orificio oval delimitado por las ramas isquiopubianas.',
        clinicalSignificance: 'La continuidad del arco iliopúbico y la línea de Shenton deben conservarse sin escalones.',
        radiologicalDensity: 'Radiolúcido (Tejido Blando/Membrana)',
      },
    ],
  },
  {
    id: 'mano-ap',
    title: 'Mano y Muñeca AP (Mano Derecha)',
    category: 'RAYOS_X',
    modality: 'Rayos X (RX)',
    projection: 'Dorsopalmar (AP Estricta)',
    description: 'Visualización osteoarticular completa: falanges distales, medias y proximales, metacarpianos, huesos del carpo y extremos distales de radio y cúbito.',
    imageUrl: '/lab-images/mano_ap.jpg',
    svgGraphic: 'hand',
    structures: [
      {
        id: 'falange-distal-3',
        name: 'Falange Distal del Tercer Dedo (Penacho Ungueal)',
        shortName: 'Falange Distal (D3)',
        x: 46,
        y: 8,
        description: 'Extremo óseo distal que aloja y soporta la uña.',
        clinicalSignificance: 'Frecuentes fracturas por aplastamiento o avulsión del tendón extensor (dedo en martillo o mallet finger).',
        radiologicalDensity: 'Radiopaco (Hueso Cortical)',
      },
      {
        id: 'falange-media-3',
        name: 'Falange Media del Tercer Dedo',
        shortName: 'Falange Media (D3)',
        x: 46,
        y: 20,
        description: 'Segmento óseo intermedio entre la articulación interfalángica proximal (IFP) y distal (IFD).',
        clinicalSignificance: 'Sitio de inserción de la bandeleta media del extensor y flexor superficial.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
      {
        id: 'tercer-metacarpiano',
        name: 'Tercer Metacarpiano (Eje Central de la Mano)',
        shortName: '3er Metacarpiano',
        x: 47,
        y: 55,
        description: 'Hueso largo central del metacarpo que se alinea rígidamente con el hueso grande y el radio.',
        clinicalSignificance: 'Eje de referencia para evaluar la longitud y rotación en fracturas metacarpianas.',
        radiologicalDensity: 'Radiopaco (Hueso Cortical denso)',
      },
      {
        id: 'primer-metacarpiano',
        name: 'Primer Metacarpiano (Pulgar)',
        shortName: '1er Metacarpiano',
        x: 62,
        y: 61,
        description: 'Metacarpiano corto y robusto con articulación trapeciometacarpiana en silla de montar.',
        clinicalSignificance: 'Sitio clásico de la fractura-luxación intraarticular de Bennett y Rolando en su base.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'sesamoideo-pulgar',
        name: 'Hueso Sesamoideo del Pulgar',
        shortName: 'Sesamoideo Pulgar',
        x: 63,
        y: 53,
        description: 'Pequeño huesecillo redondeado incluido dentro de los tendones de la articulación metacarpofalángica.',
        clinicalSignificance: 'Variante anatómica constante que no debe confundirse con un fragmento de fractura por avulsión.',
        radiologicalDensity: 'Radiopaco Redondeado',
      },
      {
        id: 'escafoides',
        name: 'Hueso Escafoides Carpiano (Pilar Radial)',
        shortName: 'Escafoides',
        x: 52,
        y: 73,
        description: 'El hueso más importante de la primera fila del carpo que une biomecánicamente ambas hileras.',
        clinicalSignificance: 'Es el hueso del carpo más fracturado tras caídas en hiperextensión; alto riesgo de necrosis avascular de su polo proximal.',
        radiologicalDensity: 'Radiopaco (Hueso Esponjoso denso)',
      },
      {
        id: 'semilunar',
        name: 'Hueso Semilunar (Lunatum)',
        shortName: 'Semilunar',
        x: 48,
        y: 76,
        description: 'Hueso con forma de semiluna que articula directamente en la fosa semilunar del radio distal.',
        clinicalSignificance: 'Propenso a necrosis avascular idiopática (Enfermedad de Kienböck) y luxación anterior en traumatismos de muñeca.',
        radiologicalDensity: 'Radiopaco (Blanco)',
      },
      {
        id: 'radio-distal',
        name: 'Epífisis Distal del Radio y Estiloides Radial',
        shortName: 'Radio Distal',
        x: 51,
        y: 88,
        description: 'Superficie articular cóncava amplia que soporta el 80% de la carga axial de la muñeca.',
        clinicalSignificance: 'Sitio de las fracturas más comunes del miembro superior (Fractura de Colles y Smith).',
        radiologicalDensity: 'Radiopaco (Hueso Cortical y Metafisario)',
      },
      {
        id: 'cubito-distal',
        name: 'Cabeza y Apófisis Estiloides del Cúbito',
        shortName: 'Cúbito Distal',
        x: 41,
        y: 88,
        description: 'Extremo distal medial que forma la articulación radiocubital distal y sostiene el fibrocartílago triangular.',
        clinicalSignificance: 'La avulsión de la estiloides cubital acompaña con frecuencia a las fracturas de radio distal.',
        radiologicalDensity: 'Radiopaco (Hueso)',
      },
    ],
  },

  // ─── 2. TOMOGRAFÍA COMPUTARIZADA (CT / TAC) ────────────────────────────────
  {
    id: 'tac-cerebro',
    title: 'TAC Cerebral Axial — Ventrículos y Ganglios Basales',
    category: 'CT',
    modality: 'Tomografía Computarizada (CT)',
    projection: 'Corte Axial Supraorbitario',
    description: 'Tomografía computarizada sin contraste a nivel de las astas frontales de los ventrículos laterales, tercer ventrículo y núcleos basales.',
    imageUrl: '/lab-images/tac_cerebro.jpg',
    svgGraphic: 'brain_ct',
    structures: [
      {
        id: 'ventriculos-laterales',
        name: 'Astas Frontales de los Ventrículos Laterales',
        shortName: 'Ventrículos Frontales',
        x: 48,
        y: 35,
        description: 'Estructuras bilaterales hipodensas (oscuras, contenido de LCR) simétricas con forma de alas.',
        clinicalSignificance: 'Su borramiento o desplazamiento indica efecto de masa por hematoma o edema cerebral agudo.',
        radiologicalDensity: 'Hipodenso (~0 a +15 HU)',
      },
      {
        id: 'tercer-ventriculo',
        name: 'Tercer Ventrículo y Septum Pellucidum',
        shortName: '3er Ventrículo',
        x: 49,
        y: 47,
        description: 'Cavidad ventricular estrecha en la línea media delimitada por los tálamos.',
        clinicalSignificance: 'La desviación de la línea media > 5 mm es indicación de descompresión neuroquirúrgica.',
        radiologicalDensity: 'Hipodenso (LCR)',
      },
      {
        id: 'nucleo-caudado',
        name: 'Cabeza del Núcleo Caudado',
        shortName: 'Núcleo Caudado',
        x: 41,
        y: 38,
        description: 'Masa de sustancia gris profunda prominente en la pared lateral de las astas frontales ventriculares.',
        clinicalSignificance: 'Área susceptible a infartos lacunares y atrofia en la Enfermedad de Huntington.',
        radiologicalDensity: 'Isodenso (+35 a +45 HU)',
      },
      {
        id: 'capsula-interna',
        name: 'Cápsula Interna (Brazo Posterior)',
        shortName: 'Cápsula Interna',
        x: 38,
        y: 45,
        description: 'Banda de sustancia blanca interpuesta entre el núcleo lenticular y el tálamo.',
        clinicalSignificance: 'Las lesiones isquémicas o hemorrágicas aquí producen hemiplejía motora pura contralateral.',
        radiologicalDensity: 'Hipodenso relativo respecto a corteza (+25 a +35 HU)',
      },
      {
        id: 'talamo-ganglios',
        name: 'Tálamo Óptico (Bilateral)',
        shortName: 'Tálamo',
        x: 44,
        y: 51,
        description: 'Gran masa de sustancia gris a ambos lados del tercer ventrículo.',
        clinicalSignificance: 'Sitio característico de hemorragias intraparenquimatosas hipertensivas y lesiones lacunares.',
        radiologicalDensity: 'Isodenso (+30 a +40 HU)',
      },
      {
        id: 'cisura-silvio',
        name: 'Cisura de Silvio / Surco Lateral',
        shortName: 'Cisura de Silvio',
        x: 27,
        y: 41,
        description: 'Profunda hendidura que separa el lóbulo frontal del lóbulo temporal.',
        clinicalSignificance: 'El borramiento precoz del ribete insular y cisura es signo temprano de isquemia de ACM.',
        radiologicalDensity: 'Hipodenso (LCR)',
      },
      {
        id: 'calota-hiperdensa',
        name: 'Calota Craneal (Hueso Cortical Hiperdenso)',
        shortName: 'Calota Craneal',
        x: 49,
        y: 7,
        description: 'Anillo óseo perimetral blanco brillante de alta atenuación radiológica (> +1000 HU).',
        clinicalSignificance: 'Evaluación de fracturas lineales o hundimientos craneales en ventana ósea.',
        radiologicalDensity: 'Hiperdenso (+1000 HU)',
      },
    ],
  },
  {
    id: 'tac-torax',
    title: 'TAC Torácico Axial (Ventana Mediastínica)',
    category: 'CT',
    modality: 'Tomografía Computarizada (CT)',
    projection: 'Corte Axial Subcarinal',
    description: 'Corte transversal del tórax a nivel de los grandes vasos: aorta ascendente, tronco pulmonar, aorta descendente y campos pulmonares.',
    imageUrl: '/lab-images/tac_torax.jpg',
    svgGraphic: 'chest_ct',
    structures: [
      {
        id: 'esternon-ct',
        name: 'Cuerpo del Esternón (Cierre Anterior)',
        shortName: 'Esternón',
        x: 50,
        y: 11,
        description: 'Placa ósea anterior hiperdensa que cierra la cavidad torácica.',
        clinicalSignificance: 'Evaluación de fracturas por desaceleración, diástasis y esternotomías.',
        radiologicalDensity: 'Hiperdenso (Hueso)',
      },
      {
        id: 'aorta-ascendente-ct',
        name: 'Aorta Ascendente',
        shortName: 'Aorta Ascendente',
        x: 51,
        y: 32,
        description: 'Gran vaso mediastínico anterior que emerge del ventrículo izquierdo.',
        clinicalSignificance: 'Calibre normal < 38-40 mm; su dilatación evalúa aneurismas torácicos o disección aórtica.',
        radiologicalDensity: 'Isodenso / Con contraste',
      },
      {
        id: 'arteria-pulmonar-ct',
        name: 'Tronco y Arteria Pulmonar Principal',
        shortName: 'Tronco Pulmonar',
        x: 59,
        y: 44,
        description: 'Gran vaso que transporta sangre desoxigenada hacia ambos pulmones.',
        clinicalSignificance: 'Sitio principal para descartar Tromboembolismo Pulmonar (TEP) mediante angio-TAC.',
        radiologicalDensity: 'Isodenso (+100 a +300 HU en Angio-TAC)',
      },
      {
        id: 'aorta-descendente-ct',
        name: 'Aorta Torácica Descendente',
        shortName: 'Aorta Descendente',
        x: 56,
        y: 59,
        description: 'Vaso cilíndrico posterior paravertebral izquierdo.',
        clinicalSignificance: 'Búsqueda del flap intimal en la disección de aorta tipo B de Stanford.',
        radiologicalDensity: 'Isodenso / Con contraste',
      },
      {
        id: 'parenquima-pulmonar-ct',
        name: 'Campos Pulmonares (Hipodensos)',
        shortName: 'Pulmón Derecho',
        x: 23,
        y: 45,
        description: 'Tejido aéreo alveolar negro muy hipodenso (-700 a -900 HU).',
        clinicalSignificance: 'Detección de neumotórax, enfisema, consolidaciones y nódulos.',
        radiologicalDensity: 'Muy Hipodenso (-800 HU)',
      },
      {
        id: 'cuerpo-vertebral-ct',
        name: 'Vértebra Torácica y Canal Raquídeo',
        shortName: 'Vértebra Torácica',
        x: 50,
        y: 72,
        description: 'Estructura ósea posterior de soporte y protección del eje neural.',
        clinicalSignificance: 'Descarte de fracturas vertebrales y metástasis osteolíticas/osteoblásticas.',
        radiologicalDensity: 'Hiperdenso (Hueso Cortical y Trabecular)',
      },
    ],
  },

  // ─── 3. RESONANCIA MAGNÉTICA (IRM / RM) ────────────────────────────────────
  {
    id: 'irm-columna',
    title: 'IRM Columna Lumbar Sagital T2',
    category: 'IRM',
    modality: 'Resonancia Magnética (IRM)',
    projection: 'Corte Sagital Medio — Ponderación T2',
    description: 'Secuencia sagital ponderada en T2 de alta resolución donde el líquido cefalorraquídeo brilla blanco (hiperintenso), permitiendo una valoración insuperable de los discos, cono medular, canal raquídeo y raíces de la cauda equina.',
    imageUrl: '/lab-images/irm_columna.jpg',
    svgGraphic: 'spine_mri',
    structures: [
      {
        id: 'cuerpo-l3-mri',
        name: 'Cuerpo Vertebral L3 (Médula Ósea)',
        shortName: 'Cuerpo L3',
        x: 38,
        y: 34,
        description: 'Señal homogénea intermedia de la médula ósea trabecular con grasa fisiológica en secuencia T2.',
        clinicalSignificance: 'Los cambios de señal tipo Modic I (edema), II (grasa) o III (esclerosis) orientan dolor discogénico crónico.',
        radiologicalDensity: 'Señal Intermedia T2',
      },
      {
        id: 'cuerpo-l5-mri',
        name: 'Cuerpo Vertebral L5 (Transición Lumbosacra)',
        shortName: 'Cuerpo L5',
        x: 39,
        y: 58,
        description: 'Último cuerpo vertebral lumbar que articula sobre la plataforma sacra S1.',
        clinicalSignificance: 'Evaluación de espondilolistesis y cambios degenerativos de plataformas articulares.',
        radiologicalDensity: 'Señal Intermedia T2',
      },
      {
        id: 'disco-l4-l5-mri',
        name: 'Núcleo Pulposo Discal L4-L5 (Hidratado)',
        shortName: 'Disco L4-L5',
        x: 38,
        y: 52,
        description: 'Estructura elástica intersomática con hidratación fisiológica hiperintensa (blanca) en secuencia T2.',
        clinicalSignificance: 'La pérdida de señal en T2 ("disco negro") indica deshidratación discal y riesgo de protrusión o hernia.',
        radiologicalDensity: 'Hiperintenso T2 / Hidratado',
      },
      {
        id: 'disco-l5-s1-mri',
        name: 'Disco Intervertebral L5-S1',
        shortName: 'Disco L5-S1',
        x: 42,
        y: 64,
        description: 'Disco intervertebral lumbosacro sometido a máxima carga mecánica.',
        clinicalSignificance: 'Localización más frecuente de hernias extruidas y compresiones radiculares en RM.',
        radiologicalDensity: 'Señal T2 / Intersomático',
      },
      {
        id: 'cono-medular',
        name: 'Cono Medular (Extremo Terminal de la Médula)',
        shortName: 'Cono Medular',
        x: 52,
        y: 14,
        description: 'Porción terminal afilada de la médula espinal que finaliza normalmente a nivel de L1-L2.',
        clinicalSignificance: 'Su descenso anormal por debajo de L2 diagnostica síndrome de médula anclada o espina bífida oculta.',
        radiologicalDensity: 'Isointenso T2 (Tejido Neural)',
      },
      {
        id: 'lcr-hiperintenso',
        name: 'Líquido Cefalorraquídeo en Canal Raquídeo (LCR T2)',
        shortName: 'LCR Hiperintenso',
        x: 52,
        y: 38,
        description: 'Señal blanca brillante (hiperintensa) de agua libre que llena el saco dural en ponderación T2.',
        clinicalSignificance: 'Proporciona un efecto mielográfico natural que delinea estenosis de canal y compresiones radiculares.',
        radiologicalDensity: 'Hiperintenso T2 Puro (Blanco Brillante)',
      },
      {
        id: 'cauda-equina',
        name: 'Cauda Equina (Raíces de la Cola de Caballo)',
        shortName: 'Cauda Equina',
        x: 53,
        y: 48,
        description: 'Conjunto de raíces nerviosas lumbosacras lineales que discurren libremente sumergidas en el LCR.',
        clinicalSignificance: 'Su compresión masiva por hernia discal extruida desencadena el Síndrome de Cola de Caballo (urgencia neuroquirúrgica).',
        radiologicalDensity: 'Hipointenso Lineal en LCR',
      },
      {
        id: 'sacro-s1-mri',
        name: 'Promontorio y Segmento Sacro S1',
        shortName: 'Promontorio S1',
        x: 46,
        y: 70,
        description: 'Plataforma ósea articular superior del hueso sacro.',
        clinicalSignificance: 'Medición de la lordosis sagital y orientación espinopélvica en resonancia.',
        radiologicalDensity: 'Señal Intermedia / Médula Grasa',
      },
    ],
  },
  {
    id: 'irm-cerebro',
    title: 'IRM Cerebral Sagital T1 (Línea Media)',
    category: 'IRM',
    modality: 'Resonancia Magnética (IRM)',
    projection: 'Corte Sagital Medio Estricto — Secuencia T1',
    description: 'Excelente resolución anatómica de la línea media cerebral: cuerpo calloso, glándula hipófisis en silla turca, tronco encefálico (mesencéfalo, puente y bulbo), cuarto ventrículo, cerebelo y unión bulbomedular.',
    imageUrl: '/lab-images/irm_cerebro.jpg',
    svgGraphic: 'brain_mri',
    structures: [
      {
        id: 'cuerpo-calloso',
        name: 'Cuerpo Calloso (Rodilla, Cuerpo y Esplenio)',
        shortName: 'Cuerpo Calloso',
        x: 52,
        y: 32,
        description: 'Gran comisura interhemisférica en forma de arco de sustancia blanca mielinizada.',
        clinicalSignificance: 'Su adelgazamiento, agenesia o lesiones focales orientan trastornos del neurodesarrollo o Esclerosis Múltiple.',
        radiologicalDensity: 'Hiperintenso T1 (Sustancia Blanca)',
      },
      {
        id: 'hipofisis-silla',
        name: 'Glándula Hipófisis (Silla Turca)',
        shortName: 'Glándula Hipófisis',
        x: 48,
        y: 55,
        description: 'Glándula endocrina maestra alojada en la fosa hipofisaria del hueso esfenoides.',
        clinicalSignificance: 'Su aumento de volumen o remodelación ósea es el hallazgo clásico de adenomas hipofisarios (micro/macroadenomas).',
        radiologicalDensity: 'Isointenso T1 / Adenohipófisis',
      },
      {
        id: 'puente-tronco',
        name: 'Tronco Encefálico (Puente de Varolio / Protuberancia)',
        shortName: 'Puente Encefálico',
        x: 55,
        y: 50,
        description: 'Prominencia anterior ventral del tronco encefálico que contiene vías motoras y núcleos de pares craneales.',
        clinicalSignificance: 'Evaluación de infartos del territorio basilar, pontinolisis y lesiones desmielinizantes.',
        radiologicalDensity: 'Isointenso T1',
      },
      {
        id: 'cuarto-ventriculo',
        name: 'Cuarto Ventrículo (Cavidad Romboidal con LCR)',
        shortName: '4to Ventrículo',
        x: 60,
        y: 54,
        description: 'Espacio ventricular posterior con forma de tienda de campaña que contiene LCR (oscuro en T1).',
        clinicalSignificance: 'Su compresión u oclusión por tumores de fosa posterior causa hidrocefalia obstructiva no comunicante.',
        radiologicalDensity: 'Hipointenso T1 (LCR Negro)',
      },
      {
        id: 'cerebelo-vermis',
        name: 'Cerebelo y Vermis Cerebeloso (Fosa Posterior)',
        shortName: 'Cerebelo',
        x: 68,
        y: 48,
        description: 'Órgano de coordinación motora en la fosa posterior con su arquitectura en folias ("árbol de la vida").',
        clinicalSignificance: 'El descenso de las amígdalas cerebelosas > 5 mm por el foramen magno diagnostica Malformación de Chiari I.',
        radiologicalDensity: 'Señal Intermedia T1',
      },
      {
        id: 'medula-cervical',
        name: 'Médula Espinal Cervical y Unión Bulbomedular',
        shortName: 'Médula Cervical',
        x: 58,
        y: 77,
        description: 'Continuación caudal del bulbo raquídeo que penetra en el canal vertebral.',
        clinicalSignificance: 'Descarte de mielopatía compresiva cervical, siringomielia o placas desmielinizantes.',
        radiologicalDensity: 'Isointenso T1',
      },
    ],
  },

  // ─── 4. ULTRASONIDO / ECOGRAFÍA (US) ───────────────────────────────────────
  {
    id: 'eco-abdominal',
    title: 'Ecografía Abdominal: Corte Hepatorrenal (Morison)',
    category: 'ULTRASONIDO',
    modality: 'Ultrasonido (US)',
    projection: 'Corte Longitudinal Intercostal / Subcostal Derecho',
    description: 'Ventana acústica estándar del protocolo FAST para valorar la interfase hepatorenal, parénquima del lóbulo hepático derecho, ecoestructura renal y búsqueda de líquido libre (hemoperitoneo/ascitis).',
    imageUrl: '/lab-images/eco_abdominal.jpg',
    svgGraphic: 'ultrasound',
    structures: [
      {
        id: 'parenquima-hepatico-us',
        name: 'Parénquima Hepático (Lóbulo Derecho)',
        shortName: 'Hígado (Lóbulo Der.)',
        x: 35,
        y: 32,
        description: 'Ecoestructura granular homogénea de ecogenicidad media (normoecoica) que sirve de patrón de referencia.',
        clinicalSignificance: 'El brillo difuso aumentado con atenuación del haz sónico posterior diagnostica esteatosis hepática.',
        radiologicalDensity: 'Isoecoico / Medio',
      },
      {
        id: 'espacio-morrison',
        name: 'Espacio de Morison (Receso Hepatorrenal con Líquido Anecoico)',
        shortName: 'Espacio de Morison',
        x: 69,
        y: 39,
        description: 'Espacio peritoneal declive entre la cara visceral hepática y el polo superior del riñón derecho que en este caso muestra líquido libre anecoico (negro puro).',
        clinicalSignificance: 'Sitio más sensible del protocolo FAST/eFAST para detección de hemoperitoneo en trauma abdominal cerrado.',
        radiologicalDensity: 'Anecoico (Negro / Líquido Libre)',
      },
      {
        id: 'corteza-renal-us',
        name: 'Corteza y Parénquima del Riñón Derecho',
        shortName: 'Corteza Renal',
        x: 48,
        y: 64,
        description: 'Banda parenquimatosa periférica que debe ser discretamente hipoecoica respecto al hígado adyacente.',
        clinicalSignificance: 'La pérdida de diferenciación corticomedular o hiperecogenicidad cortical traduce nefropatía médica crónica.',
        radiologicalDensity: 'Hipoecoico relativo',
      },
      {
        id: 'seno-renal-us',
        name: 'Seno Renal y Sistema Colector',
        shortName: 'Seno Renal',
        x: 55,
        y: 56,
        description: 'Complejo ecogénico central blanco brillante formado por la grasa del hilio, vasos y cálices renales.',
        clinicalSignificance: 'La separación o dilatación anecoica central de los cálices diagnostica hidronefrosis obstructiva.',
        radiologicalDensity: 'Hiperecoico Central (Grasa y Cálices)',
      },
      {
        id: 'diafragma-hiperecoico',
        name: 'Cúpula Diafragmática (Línea Hiperecoica)',
        shortName: 'Diafragma (Hiperecoico)',
        x: 68,
        y: 27,
        description: 'Banda curva hiperecoica blanca brillante reflectante generada por el cambio de impedancia acústica con la base pulmonar.',
        clinicalSignificance: 'El artefacto en espejo hepático por encima del diafragma es normal; su reemplazo por fluido define derrame pleural.',
        radiologicalDensity: 'Hiperecoico (Blanco reflectante)',
      },
    ],
  },
]
